### ISSUE TITLE
Why need Patroller

### ISSUE THREAD

**Issue by vincent-pli** [kubernetes-sigs/cluster-api-provider-nested#208]
No matter `upward`(UWController) or `downward`(MCController) synchronization are all based on `informer`. so why we still need a 60s polling `Patroller` to compare resource from super and tenant manually?

Is some potential risk for `informer`? thanks.
@Fei-Guo @charleszheng44 @christopherhein

**Comment by Fei-Guo** [comment]
There are rare cases where tenant and super can be inconsistent. For example, deleting pods requires kubelet to delete the Pod with graceperiod 0. In VC, it is the syncer's duty to finally delete the tenant Pods with graceperiod 0. If the super cluster Pod is deleted too quickly, the syncer may not be able to delete the tenant Pod (the object in super cluster is gone and syncer cannot find the tenant Pod through the label in super Pod). Another example is that, if tenant use a tight loop to update object with different spec A & B in turn, the state may also be inconsistent after the loop is done due to informer cache delay. Besides above, if the syncer or super cluster crashes during synchronization, the state can be inconsistent(e.g., the object in tenant is deleted when syncer is offline, syncer needs to perform full scan when it is restarted). Indeed, we can resolve all those problems by enhancing the component restart code path or syncer code to even check the object revision number. We choose a conservative periodic check to ease the error handling code in other code paths for simplicity. I am sure there are other design choices of handling these problems without periodic check. Note that debugging the inconsistent problem in production environment will be extremely difficult hence the periodic check will be our last resort. We do have metrics/logs to record inconsistency objects for further investigation.

**Comment by vincent-pli** [comment]
Thanks @Fei-Guo , very useful, I will keep the issue open I guess people may has same question.

**Comment by christopherhein** [comment]
@vincent-pli would you like to turn this into a PR with these notes written up in the virtualcluster readme?
