### ISSUE TITLE
High Level User Stories

### ISSUE THREAD

**Issue by christopherhein** [kubernetes-sigs/cluster-api-provider-nested#5]
1. As a control plane operator, I want my Kubernetes control plane to have multiple replicas to meet my zero down time needs.
2. As a control plane operator, I want to be able declare how each control plane is configured.
3. As a control plane operator, I want to be able to rotate the certificates on all components so that my cluster continues to run
4. As a developer, I want to be able to use control plane level resources without conflicting with another control plane
5. As a control plane operator, I want to be able to upgrade to a minor version so my cluster remains supported.
6. As a control plane operator, I want to be able to know my cluster is working properly after it's been created.

**Comment by christopherhein** [comment]
@salaxander @Fei-Guo @weiling61 @charleszheng44

**Comment by christopherhein** [comment]
Please add more User Stories for CAPN

**Comment by christopherhein** [comment]
We need to add a story about multi-tenancy use cases.

**Comment by brightzheng100** [comment]
There should have some level of delegation from super admin to tenant / nested cluster admin(s) so these use cases might be valid as well:

- As a tenant / nested cluster admin, I want to be able to connect to an authn/authz provider so that I can onboard my users;
- As a tenant / nested cluster admin, I want to be able to act like a real K8s admin to create cluster-wide objects, e.g. CRDs, namespaces, within my tenant / nested cluster and grant permissions to my users/roles;
- As a tenant / nested cluster admin, I want to be able to upgrade my nested cluster(s) to available, supported K8s versions independently

**Comment by christopherhein** [comment]
Thanks @brightzheng100
